title: Introducción a la Ciencia de Datos para Científicos Sociales
description: Materiales del curso desarrollado para la Facultad de Humanidades, Ciencias Sociales y Humanidades de la Universidad Nacional de Santiago del Estero
show_downloads: false
theme: jekyll-theme-slate
